app = "client-centric-files"
primary_region = "iad"

[build]
  dockerfile = "Dockerfile"

[env]
  NODE_ENV = "production"

[[services]]
  internal_port = 3000
  protocol = "tcp"

  [services.concurrency]
    type = "connections"
    soft_limit = 25
    hard_limit = 50

  [[services.ports]]
    port = 80

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    restart_limit = 0
